# Generated by Django 5.2.11 on 2026-02-28 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalylog',
            name='reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.powerreading'),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='severity',
            field=models.IntegerField(),
        ),
    ]
