# Generated by Django 5.2.11 on 2026-03-01 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_anomalylog_reading_alter_anomalylog_severity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='powerreading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalylog',
            name='reading_type',
            field=models.CharField(choices=[('power_w', 'Power (W)'), ('voltage', 'Voltage (V)'), ('current_a', 'Current (A)'), ('energy_kwh', 'Energy (kWh)'), ('power_factor', 'Power Factor')], db_index=True, default='power_w', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerreading',
            name='reading_type',
            field=models.CharField(choices=[('power_w', 'Power (W)'), ('voltage', 'Voltage (V)'), ('current_a', 'Current (A)'), ('energy_kwh', 'Energy (kWh)'), ('power_factor', 'Power Factor')], db_index=True, default='power_w', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_logs', to='myapp.powerreading'),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2),
        ),
        migrations.AlterField(
            model_name='anomalylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='anomalylog',
            index=models.Index(fields=['asset', 'reading_type', '-timestamp'], name='myapp_anoma_asset_i_bfbc43_idx'),
        ),
        migrations.AddIndex(
            model_name='powerreading',
            index=models.Index(fields=['asset', 'reading_type', '-timestamp'], name='myapp_power_asset_i_bf4e35_idx'),
        ),
    ]
